apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test-cluster-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-project-1-430302
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: test-project-1-430302
    spec:
      containers:
        - name: test-project-1-430302
          image: gcr.io/test-project-1-430302/IMAGE:TAG
          ports:
            - containerPort: 3008
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m